metadata_dir = "/var/lib/garage/meta"
data_dir     = "/var/lib/garage/data"
replication_factor = 1

rpc_bind_addr   = "0.0.0.0:3901"
rpc_public_addr = "127.0.0.1:3901"
# Generate a real secret with: openssl rand -hex 32
rpc_secret = "0000000000000000000000000000000000000000000000000000000000000001"

[s3_api]
s3_region    = "garage"
api_bind_addr = "0.0.0.0:3900"

[admin]
api_bind_addr = "0.0.0.0:3903"
admin_token   = "garage-admin-token"
