apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{container_name=~"scoring-.*"} |= "${__trace.traceId}"'
      serviceMap:
        datasourceUid: prometheus
      lokiSearch:
        datasourceUid: loki
