allowBuilds:
  '@firebase/util': true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
onlyBuiltDependencies:
  - msgpackr-extract
  - esbuild
  - protobufjs
  - '@firebase/util'
